###### Author: ard12sgf1960
###### Email: sgfpcb@gmail.com  
###### Date: 24/03/2025  
###### Revision: version # 2.0
###### License: Public Domain

# Project: Using WiFiSetupLibrary.h

- Connect to any network.
- No need to hard code credentials.
- I have found that the great WiFiManager library can sometimes be too big for smaller memory devices.
- Therefore, with the help of Gemini, I wrote this library.

> ESP32 devices with WiFi capabilities.

### The library requires...

    WiFi.h
    WebServer.h
    EEPROM.h

### Code allows for...

- Arduino Thing credential inputs.  
- Forcing Override AutoConnect, Force AutoConnect, Degug Messages functions.
- Code writer can choose Access Point Name and Password

### The library allows calls for obtaining...

    SSID name: getSSID()
    Password: getPassword()
    Device ID: getDeviceID()
    Secret Code: getSecretCode()

### Public functions

    handleClient()    - call to obtain available networks and enter credentials. Data save in device EEPROM 
    isSetupComplete() - a boolean check to see if user has completed the setup
    setOverrideAutoConnect(bool overrideAutoConnect);
    setForceAutoConnect(bool forceAutoConnect);
    setShowDebug(bool showDebug);

    WiFiSetup.begin() takes 3 parameters overrideAutoConnect = false, bool forceAutoConnect = false, int debugLevel = 0
        If forceAutoConnect is true, then the device will auto connect, regardless of the EEPROM setting.
        If overrideAutoConnect is true, then the device will start the AP, regardless of the EEPROM setting.
        If neither are true, then the device will follow the EEPROM settings.
        showDebug. false=No messages. true=All messages (to serial monitor)

=== Folder structure

....
 Your .ino sketch folder     => Arduino sketch folder
  ├── Your sketch.ino        => main Arduino file
    ├── WiFISetupLibrary.h     => My created library
      ├── WiFi.h                 => library that contains WiFi routines
      ├── WebServer.h            => library to manage serving web pages
      ├── EEPROM.h               => library file to manage writing and reading to EEPROM
....

== Function

The library checks the devices EEPROM storage and if AutoConnect is selected
reads the memory and if data exits will attempt to connect to the stored network.
Otherwise, it will start the devices Access Point and show up on a mobile or PC's network list.
The user should connect to this network and open a web page at 168.192.4.1 where a list of available networks is shown.
Select your network and add the password and Arduiono Device credentials.
The device will then attempt connect to the network and then Arduino Cloud.
The AP will close and the device should be connected to the network.
The credentials will be saved to EEPROM for auto connect.

=== License
This project is released under a {PUBLIC} License.

=== Contributing
To contribute to this project please contact: sgfpcb@gmail.com

=== BOM

|===
| ID | Part name           | Part number     | Quantity     |Price   | Webpage                             
| A1 | M5 Atom S3          | SKU: C123       | 1            |£15.50  | https://docs.m5stack.com/en/core/AtomS3 
| A2 | M5 Relay Module     | SKU: U023       | 1            |£3.50   | https://shop.m5stack.com/products/mini-3a-relay-unit                                         
|===

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
